name: Scrape Data

on:
  #schedule:
    #- cron: "*/120 * * * *" # Runs Every Two hour
  workflow_dispatch:

jobs:
  run-scraper:
    uses: beckn/leaderboard/.github/workflows/scrapper_for_data_repo.yml@main
    permissions:
      issues: read
      pull-requests: read
      contents: write
    secrets: inherit
