name: Scrape Data

on:
  #schedule:
    #- cron: "*/120 * * * *" # Runs Every Two hour
  workflow_dispatch:

jobs:
  run-scraper:
    uses: beckn/leaderboard/.github/workflows/scrapper_for_data_repo.yml@main
    if: github.ref == 'refs/heads/develop'
    permissions:
      issues: read
      pull-requests: read
      contents: write
    secrets: inherit
    with:
      slack-eod-channel: ${{ vars.SLACK_EOD_CHANNEL }}
