name: Scrape Data

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run-scraper:
    uses: beckn/leaderboard/.github/workflows/scrapper_new_leaderboard.yml@main
    secrets:
      GIT_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass GITHUB_TOKEN as GIT_ACCESS_TOKEN
    permissions:
      issues: read
      pull-requests: read
      contents: write
    with:
      projects-board-id: PVT_kwDOA3tJis4AdNYF
  
